#pragma once
// Note: this file is automatically generated, any changes will be lost.
// Modify gfx.hpp.in instead.
#include <array>
#include <cstdint>
#include <string_view>

namespace GFX
{
constexpr std::int32_t GOSTEK_STOPA = 1;
constexpr std::int32_t GOSTEK_STOPA2 = 2;
constexpr std::int32_t GOSTEK_NOGA = 3;
constexpr std::int32_t GOSTEK_NOGA2 = 4;
constexpr std::int32_t GOSTEK_UDO = 5;
constexpr std::int32_t GOSTEK_UDO2 = 6;
constexpr std::int32_t GOSTEK_BIODRO = 7;
constexpr std::int32_t GOSTEK_BIODRO2 = 8;
constexpr std::int32_t GOSTEK_KLATA = 9;
constexpr std::int32_t GOSTEK_KLATA2 = 10;
constexpr std::int32_t GOSTEK_MORDA = 11;
constexpr std::int32_t GOSTEK_MORDA2 = 12;
constexpr std::int32_t GOSTEK_RAMIE = 13;
constexpr std::int32_t GOSTEK_RAMIE2 = 14;
constexpr std::int32_t GOSTEK_REKA = 15;
constexpr std::int32_t GOSTEK_REKA2 = 16;
constexpr std::int32_t GOSTEK_DLON = 17;
constexpr std::int32_t GOSTEK_DLON2 = 18;
constexpr std::int32_t GOSTEK_LANCUCH = 19;
constexpr std::int32_t GOSTEK_HELM = 20;
constexpr std::int32_t GOSTEK_HELM2 = 21;
constexpr std::int32_t GOSTEK_BADGE = 22;
constexpr std::int32_t GOSTEK_BADGE2 = 23;
constexpr std::int32_t GOSTEK_CYGARO = 24;
constexpr std::int32_t GOSTEK_CYGARO2 = 25;
constexpr std::int32_t GOSTEK_METAL = 26;
constexpr std::int32_t GOSTEK_METAL2 = 27;
constexpr std::int32_t GOSTEK_ZLOTO = 28;
constexpr std::int32_t GOSTEK_ZLOTO2 = 29;
constexpr std::int32_t GOSTEK_ZLOTYLANCUCH = 30;
constexpr std::int32_t GOSTEK_KAP = 31;
constexpr std::int32_t GOSTEK_KAP2 = 32;
constexpr std::int32_t GOSTEK_DRED = 33;
constexpr std::int32_t GOSTEK_HAIR1 = 34;
constexpr std::int32_t GOSTEK_HAIR12 = 35;
constexpr std::int32_t GOSTEK_HAIR2 = 36;
constexpr std::int32_t GOSTEK_HAIR22 = 37;
constexpr std::int32_t GOSTEK_HAIR3 = 38;
constexpr std::int32_t GOSTEK_HAIR32 = 39;
constexpr std::int32_t GOSTEK_HAIR4 = 40;
constexpr std::int32_t GOSTEK_HAIR42 = 41;
constexpr std::int32_t GOSTEK_KAMIZELKA = 42;
constexpr std::int32_t GOSTEK_KAMIZELKA2 = 43;
constexpr std::int32_t GOSTEK_RANNY_KLATA = 44;
constexpr std::int32_t GOSTEK_RANNY_KLATA2 = 45;
constexpr std::int32_t GOSTEK_RANNY_MORDA = 46;
constexpr std::int32_t GOSTEK_RANNY_MORDA2 = 47;
constexpr std::int32_t GOSTEK_RANNY_NOGA = 48;
constexpr std::int32_t GOSTEK_RANNY_NOGA2 = 49;
constexpr std::int32_t GOSTEK_RANNY_RAMIE = 50;
constexpr std::int32_t GOSTEK_RANNY_RAMIE2 = 51;
constexpr std::int32_t GOSTEK_RANNY_REKA = 52;
constexpr std::int32_t GOSTEK_RANNY_REKA2 = 53;
constexpr std::int32_t GOSTEK_RANNY_UDO = 54;
constexpr std::int32_t GOSTEK_RANNY_UDO2 = 55;
constexpr std::int32_t GOSTEK_RANNY_BIODRO = 56;
constexpr std::int32_t GOSTEK_RANNY_BIODRO2 = 57;
constexpr std::int32_t GOSTEK_LECISTOPA = 58;
constexpr std::int32_t GOSTEK_LECISTOPA2 = 59;
constexpr std::int32_t GOSTEK_TEAM2_STOPA = 60;
constexpr std::int32_t GOSTEK_TEAM2_STOPA2 = 61;
constexpr std::int32_t GOSTEK_TEAM2_NOGA = 62;
constexpr std::int32_t GOSTEK_TEAM2_NOGA2 = 63;
constexpr std::int32_t GOSTEK_TEAM2_UDO = 64;
constexpr std::int32_t GOSTEK_TEAM2_UDO2 = 65;
constexpr std::int32_t GOSTEK_TEAM2_BIODRO = 66;
constexpr std::int32_t GOSTEK_TEAM2_BIODRO2 = 67;
constexpr std::int32_t GOSTEK_TEAM2_KLATA = 68;
constexpr std::int32_t GOSTEK_TEAM2_KLATA2 = 69;
constexpr std::int32_t GOSTEK_TEAM2_MORDA = 70;
constexpr std::int32_t GOSTEK_TEAM2_MORDA2 = 71;
constexpr std::int32_t GOSTEK_TEAM2_RAMIE = 72;
constexpr std::int32_t GOSTEK_TEAM2_RAMIE2 = 73;
constexpr std::int32_t GOSTEK_TEAM2_REKA = 74;
constexpr std::int32_t GOSTEK_TEAM2_REKA2 = 75;
constexpr std::int32_t GOSTEK_TEAM2_DLON = 76;
constexpr std::int32_t GOSTEK_TEAM2_DLON2 = 77;
constexpr std::int32_t GOSTEK_TEAM2_LANCUCH = 78;
constexpr std::int32_t GOSTEK_TEAM2_HELM = 79;
constexpr std::int32_t GOSTEK_TEAM2_HELM2 = 80;
constexpr std::int32_t GOSTEK_TEAM2_BADGE = 81;
constexpr std::int32_t GOSTEK_TEAM2_BADGE2 = 82;
constexpr std::int32_t GOSTEK_TEAM2_CYGARO = 83;
constexpr std::int32_t GOSTEK_TEAM2_CYGARO2 = 84;
constexpr std::int32_t GOSTEK_TEAM2_METAL = 85;
constexpr std::int32_t GOSTEK_TEAM2_METAL2 = 86;
constexpr std::int32_t GOSTEK_TEAM2_ZLOTO = 87;
constexpr std::int32_t GOSTEK_TEAM2_ZLOTO2 = 88;
constexpr std::int32_t GOSTEK_TEAM2_ZLOTYLANCUCH = 89;
constexpr std::int32_t GOSTEK_TEAM2_KAP = 90;
constexpr std::int32_t GOSTEK_TEAM2_KAP2 = 91;
constexpr std::int32_t GOSTEK_TEAM2_DRED = 92;
constexpr std::int32_t GOSTEK_TEAM2_HAIR1 = 93;
constexpr std::int32_t GOSTEK_TEAM2_HAIR12 = 94;
constexpr std::int32_t GOSTEK_TEAM2_HAIR2 = 95;
constexpr std::int32_t GOSTEK_TEAM2_HAIR22 = 96;
constexpr std::int32_t GOSTEK_TEAM2_HAIR3 = 97;
constexpr std::int32_t GOSTEK_TEAM2_HAIR32 = 98;
constexpr std::int32_t GOSTEK_TEAM2_HAIR4 = 99;
constexpr std::int32_t GOSTEK_TEAM2_HAIR42 = 100;
constexpr std::int32_t GOSTEK_TEAM2_KAMIZELKA = 101;
constexpr std::int32_t GOSTEK_TEAM2_KAMIZELKA2 = 102;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_KLATA = 103;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_KLATA2 = 104;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_MORDA = 105;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_MORDA2 = 106;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_NOGA = 107;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_NOGA2 = 108;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_RAMIE = 109;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_RAMIE2 = 110;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_REKA = 111;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_REKA2 = 112;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_UDO = 113;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_UDO2 = 114;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_BIODRO = 115;
constexpr std::int32_t GOSTEK_TEAM2_RANNY_BIODRO2 = 116;
constexpr std::int32_t GOSTEK_TEAM2_LECISTOPA = 117;
constexpr std::int32_t GOSTEK_TEAM2_LECISTOPA2 = 118;
constexpr std::int32_t GOSTEK_PARA_ROPE = 119;
constexpr std::int32_t GOSTEK_PARA = 120;
constexpr std::int32_t GOSTEK_PARA2 = 121;
constexpr std::int32_t WEAPONS_SHELL = 122;
constexpr std::int32_t WEAPONS_BULLET = 123;
constexpr std::int32_t WEAPONS_SMUDGE = 124;
constexpr std::int32_t WEAPONS_MISSILE = 125;
constexpr std::int32_t WEAPONS_CLUSTER = 126;
constexpr std::int32_t WEAPONS_CLUSTER_GRENADE = 127;
constexpr std::int32_t WEAPONS_FRAG_GRENADE = 128;
constexpr std::int32_t WEAPONS_AK74 = 129;
constexpr std::int32_t WEAPONS_AK74_2 = 130;
constexpr std::int32_t WEAPONS_AK74_CLIP = 131;
constexpr std::int32_t WEAPONS_AK74_CLIP2 = 132;
constexpr std::int32_t WEAPONS_AK74_SHELL = 133;
constexpr std::int32_t WEAPONS_AK74_BULLET = 134;
constexpr std::int32_t WEAPONS_AK74_FIRE = 135;
constexpr std::int32_t WEAPONS_MINIMI = 136;
constexpr std::int32_t WEAPONS_MINIMI_2 = 137;
constexpr std::int32_t WEAPONS_MINIMI_CLIP = 138;
constexpr std::int32_t WEAPONS_MINIMI_CLIP2 = 139;
constexpr std::int32_t WEAPONS_MINIMI_SHELL = 140;
constexpr std::int32_t WEAPONS_MINIMI_BULLET = 141;
constexpr std::int32_t WEAPONS_MINIMI_FIRE = 142;
constexpr std::int32_t WEAPONS_RUGER = 143;
constexpr std::int32_t WEAPONS_RUGER_2 = 144;
constexpr std::int32_t WEAPONS_RUGER_SHELL = 145;
constexpr std::int32_t WEAPONS_RUGER_BULLET = 146;
constexpr std::int32_t WEAPONS_RUGER_FIRE = 147;
constexpr std::int32_t WEAPONS_MP5 = 148;
constexpr std::int32_t WEAPONS_MP5_2 = 149;
constexpr std::int32_t WEAPONS_MP5_CLIP = 150;
constexpr std::int32_t WEAPONS_MP5_CLIP2 = 151;
constexpr std::int32_t WEAPONS_MP5_SHELL = 152;
constexpr std::int32_t WEAPONS_MP5_BULLET = 153;
constexpr std::int32_t WEAPONS_MP5_FIRE = 154;
constexpr std::int32_t WEAPONS_SPAS = 155;
constexpr std::int32_t WEAPONS_SPAS_2 = 156;
constexpr std::int32_t WEAPONS_SPAS_SHELL = 157;
constexpr std::int32_t WEAPONS_SPAS_BULLET = 158;
constexpr std::int32_t WEAPONS_SPAS_FIRE = 159;
constexpr std::int32_t WEAPONS_M79 = 160;
constexpr std::int32_t WEAPONS_M79_2 = 161;
constexpr std::int32_t WEAPONS_M79_CLIP = 162;
constexpr std::int32_t WEAPONS_M79_CLIP2 = 163;
constexpr std::int32_t WEAPONS_M79_SHELL = 164;
constexpr std::int32_t WEAPONS_M79_BULLET = 165;
constexpr std::int32_t WEAPONS_M79_FIRE = 166;
constexpr std::int32_t WEAPONS_DEAGLES = 167;
constexpr std::int32_t WEAPONS_DEAGLES_2 = 168;
constexpr std::int32_t WEAPONS_N_DEAGLES = 169;
constexpr std::int32_t WEAPONS_N_DEAGLES_2 = 170;
constexpr std::int32_t WEAPONS_DEAGLES_CLIP = 171;
constexpr std::int32_t WEAPONS_DEAGLES_CLIP2 = 172;
constexpr std::int32_t WEAPONS_DEAGLES_SHELL = 173;
constexpr std::int32_t WEAPONS_DEAGLES_BULLET = 174;
constexpr std::int32_t WEAPONS_DEAGLES_FIRE = 175;
constexpr std::int32_t WEAPONS_STEYR = 176;
constexpr std::int32_t WEAPONS_STEYR_2 = 177;
constexpr std::int32_t WEAPONS_STEYR_CLIP = 178;
constexpr std::int32_t WEAPONS_STEYR_CLIP2 = 179;
constexpr std::int32_t WEAPONS_STEYR_SHELL = 180;
constexpr std::int32_t WEAPONS_STEYR_BULLET = 181;
constexpr std::int32_t WEAPONS_STEYR_FIRE = 182;
constexpr std::int32_t WEAPONS_BARRETT = 183;
constexpr std::int32_t WEAPONS_BARRETT_2 = 184;
constexpr std::int32_t WEAPONS_BARRETT_CLIP = 185;
constexpr std::int32_t WEAPONS_BARRETT_CLIP2 = 186;
constexpr std::int32_t WEAPONS_BARRETT_SHELL = 187;
constexpr std::int32_t WEAPONS_BARRETT_BULLET = 188;
constexpr std::int32_t WEAPONS_BARRETT_FIRE = 189;
constexpr std::int32_t WEAPONS_MINIGUN = 190;
constexpr std::int32_t WEAPONS_MINIGUN_2 = 191;
constexpr std::int32_t WEAPONS_MINIGUN_CLIP = 192;
constexpr std::int32_t WEAPONS_MINIGUN_SHELL = 193;
constexpr std::int32_t WEAPONS_MINIGUN_BULLET = 194;
constexpr std::int32_t WEAPONS_MINIGUN_FIRE = 195;
constexpr std::int32_t WEAPONS_SOCOM = 196;
constexpr std::int32_t WEAPONS_SOCOM_2 = 197;
constexpr std::int32_t WEAPONS_N_SOCOM = 198;
constexpr std::int32_t WEAPONS_N_SOCOM_2 = 199;
constexpr std::int32_t WEAPONS_SOCOM_CLIP = 200;
constexpr std::int32_t WEAPONS_SOCOM_CLIP2 = 201;
constexpr std::int32_t WEAPONS_COLT_SHELL = 202;
constexpr std::int32_t WEAPONS_COLT_BULLET = 203;
constexpr std::int32_t WEAPONS_SOCOM_FIRE = 204;
constexpr std::int32_t WEAPONS_BOW = 205;
constexpr std::int32_t WEAPONS_BOW_2 = 206;
constexpr std::int32_t WEAPONS_BOW_S = 207;
constexpr std::int32_t WEAPONS_BOW_A = 208;
constexpr std::int32_t WEAPONS_N_BOW = 209;
constexpr std::int32_t WEAPONS_N_BOW_2 = 210;
constexpr std::int32_t WEAPONS_ARROW = 211;
constexpr std::int32_t WEAPONS_BOW_FIRE = 212;
constexpr std::int32_t WEAPONS_FLAMER = 213;
constexpr std::int32_t WEAPONS_FLAMER_2 = 214;
constexpr std::int32_t WEAPONS_FLAMER_FIRE = 215;
constexpr std::int32_t WEAPONS_KNIFE = 216;
constexpr std::int32_t WEAPONS_KNIFE2 = 217;
constexpr std::int32_t WEAPONS_CHAINSAW = 218;
constexpr std::int32_t WEAPONS_CHAINSAW2 = 219;
constexpr std::int32_t WEAPONS_CHAINSAW_FIRE = 220;
constexpr std::int32_t WEAPONS_LAW = 221;
constexpr std::int32_t WEAPONS_LAW_2 = 222;
constexpr std::int32_t WEAPONS_LAW_FIRE = 223;
constexpr std::int32_t WEAPONS_M2 = 224;
constexpr std::int32_t WEAPONS_M2_2 = 225;
constexpr std::int32_t WEAPONS_M2_STAT = 226;
constexpr std::int32_t SPARKS_SMOKE = 227;
constexpr std::int32_t SPARKS_LILFIRE = 228;
constexpr std::int32_t SPARKS_ODPRYSK = 229;
constexpr std::int32_t SPARKS_BLOOD = 230;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE1 = 231;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE2 = 232;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE3 = 233;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE4 = 234;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE5 = 235;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE6 = 236;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE7 = 237;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE8 = 238;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE9 = 239;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE10 = 240;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE11 = 241;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE12 = 242;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE13 = 243;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE14 = 244;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE15 = 245;
constexpr std::int32_t SPARKS_EXPLOSION_EXPLODE16 = 246;
constexpr std::int32_t SPARKS_BIGSMOKE = 247;
constexpr std::int32_t SPARKS_SPAWNSPARK = 248;
constexpr std::int32_t SPARKS_PIN = 249;
constexpr std::int32_t SPARKS_LILSMOKE = 250;
constexpr std::int32_t SPARKS_STUFF = 251;
constexpr std::int32_t SPARKS_CYGARO = 252;
constexpr std::int32_t SPARKS_PLOMYK = 253;
constexpr std::int32_t SPARKS_BLACKSMOKE = 254;
constexpr std::int32_t SPARKS_RAIN = 255;
constexpr std::int32_t SPARKS_SAND = 256;
constexpr std::int32_t SPARKS_ODLAMEK1 = 257;
constexpr std::int32_t SPARKS_ODLAMEK2 = 258;
constexpr std::int32_t SPARKS_ODLAMEK3 = 259;
constexpr std::int32_t SPARKS_ODLAMEK4 = 260;
constexpr std::int32_t SPARKS_SKRAWEK = 261;
constexpr std::int32_t SPARKS_PUFF = 262;
constexpr std::int32_t SPARKS_SNOW = 263;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE1 = 264;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE2 = 265;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE3 = 266;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE4 = 267;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE5 = 268;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE6 = 269;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE7 = 270;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE8 = 271;
constexpr std::int32_t SPARKS_EXPLOSION_SMOKE9 = 272;
constexpr std::int32_t SPARKS_SPLAT = 273;
constexpr std::int32_t SPARKS_MINISMOKE = 274;
constexpr std::int32_t SPARKS_BIGSMOKE2 = 275;
constexpr std::int32_t SPARKS_JETFIRE = 276;
constexpr std::int32_t SPARKS_LILBLOOD = 277;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE1 = 278;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE2 = 279;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE3 = 280;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE4 = 281;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE5 = 282;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE6 = 283;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE7 = 284;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE8 = 285;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE9 = 286;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE10 = 287;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE11 = 288;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE12 = 289;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE13 = 290;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE14 = 291;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE15 = 292;
constexpr std::int32_t SPARKS_FLAMES_EXPLODE16 = 293;
constexpr std::int32_t INTERFACE_SIGHT = 294;
constexpr std::int32_t INTERFACE_GUNS_DEAGLES = 295;
constexpr std::int32_t INTERFACE_GUNS_MP5 = 296;
constexpr std::int32_t INTERFACE_GUNS_AK74 = 297;
constexpr std::int32_t INTERFACE_GUNS_STEYR = 298;
constexpr std::int32_t INTERFACE_GUNS_SPAS = 299;
constexpr std::int32_t INTERFACE_GUNS_RUGER = 300;
constexpr std::int32_t INTERFACE_GUNS_M79 = 301;
constexpr std::int32_t INTERFACE_GUNS_BARRETT = 302;
constexpr std::int32_t INTERFACE_GUNS_MINIMI = 303;
constexpr std::int32_t INTERFACE_GUNS_MINIGUN = 304;
constexpr std::int32_t INTERFACE_GUNS_SOCOM = 305;
constexpr std::int32_t INTERFACE_GUNS_KNIFE = 306;
constexpr std::int32_t INTERFACE_GUNS_CHAINSAW = 307;
constexpr std::int32_t INTERFACE_GUNS_LAW = 308;
constexpr std::int32_t INTERFACE_GUNS_FLAMER = 309;
constexpr std::int32_t INTERFACE_GUNS_BOW = 310;
constexpr std::int32_t INTERFACE_GUNS_FIST = 311;
constexpr std::int32_t INTERFACE_GUNS_M2 = 312;
constexpr std::int32_t INTERFACE_STAR = 313;
constexpr std::int32_t INTERFACE_FRIEND = 314;
constexpr std::int32_t INTERFACE_MIC = 315;
constexpr std::int32_t INTERFACE_CONNECTION = 316;
constexpr std::int32_t INTERFACE_SMALLDOT = 317;
constexpr std::int32_t INTERFACE_DEADDOT = 318;
constexpr std::int32_t INTERFACE_MUTE = 319;
constexpr std::int32_t INTERFACE_PROT = 320;
constexpr std::int32_t INTERFACE_SCROLL = 321;
constexpr std::int32_t INTERFACE_BOT = 322;
constexpr std::int32_t INTERFACE_CURSOR = 323;
constexpr std::int32_t INTERFACE_HEALTH = 324;
constexpr std::int32_t INTERFACE_AMMO = 325;
constexpr std::int32_t INTERFACE_JET = 326;
constexpr std::int32_t INTERFACE_HEALTH_BAR = 327;
constexpr std::int32_t INTERFACE_JET_BAR = 328;
constexpr std::int32_t INTERFACE_RELOAD_BAR = 329;
constexpr std::int32_t INTERFACE_BACK = 330;
constexpr std::int32_t INTERFACE_OVERLAY = 331;
constexpr std::int32_t INTERFACE_NADE = 332;
constexpr std::int32_t INTERFACE_NOFLAG = 333;
constexpr std::int32_t INTERFACE_FLAG = 334;
constexpr std::int32_t INTERFACE_CLUSTER_NADE = 335;
constexpr std::int32_t INTERFACE_DOT = 336;
constexpr std::int32_t INTERFACE_FIRE_BAR = 337;
constexpr std::int32_t INTERFACE_FIRE_BAR_R = 338;
constexpr std::int32_t INTERFACE_VEST_BAR = 339;
constexpr std::int32_t INTERFACE_MENUCURSOR = 340;
constexpr std::int32_t INTERFACE_ARROW = 341;
constexpr std::int32_t INTERFACE_TITLE_L = 342;
constexpr std::int32_t INTERFACE_TITLE_R = 343;
constexpr std::int32_t OBJECTS_FLAG = 344;
constexpr std::int32_t OBJECTS_INFFLAG = 345;
constexpr std::int32_t OBJECTS_MEDIKIT = 346;
constexpr std::int32_t OBJECTS_GRENADEKIT = 347;
constexpr std::int32_t OBJECTS_FLAMERKIT = 348;
constexpr std::int32_t OBJECTS_PREDATORKIT = 349;
constexpr std::int32_t OBJECTS_VESTKIT = 350;
constexpr std::int32_t OBJECTS_BERSERKERKIT = 351;
constexpr std::int32_t OBJECTS_CLUSTERKIT = 352;
constexpr std::int32_t OBJECTS_ILUM = 353;
constexpr std::int32_t OBJECTS_FLAG_HANDLE = 354;
constexpr std::int32_t END = 354;
}; // namespace GFX

namespace GFXG
{
constexpr std::int32_t GOSTEK = 1;
constexpr std::int32_t INTERFACE = 2;
constexpr std::int32_t OBJECTS = 3;
constexpr std::int32_t SPARKS = 4;
constexpr std::int32_t WEAPONS = 5;
}; // namespace GFXG

struct GfxDataEntry
{
  std::int32_t ID;
  std::int32_t Group;
  std::string_view Path;
  std::uint32_t ColorKey;
};
constexpr std::array<GfxDataEntry, 354> GFXData = {
  GfxDataEntry{GFX::GOSTEK_STOPA, GFXG::GOSTEK, "gostek-gfx/stopa.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_STOPA2, GFXG::GOSTEK, "gostek-gfx/stopa2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_NOGA, GFXG::GOSTEK, "gostek-gfx/noga.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_NOGA2, GFXG::GOSTEK, "gostek-gfx/noga2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_UDO, GFXG::GOSTEK, "gostek-gfx/udo.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_UDO2, GFXG::GOSTEK, "gostek-gfx/udo2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_BIODRO, GFXG::GOSTEK, "gostek-gfx/biodro.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_BIODRO2, GFXG::GOSTEK, "gostek-gfx/biodro2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_KLATA, GFXG::GOSTEK, "gostek-gfx/klata.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_KLATA2, GFXG::GOSTEK, "gostek-gfx/klata2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_MORDA, GFXG::GOSTEK, "gostek-gfx/morda.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_MORDA2, GFXG::GOSTEK, "gostek-gfx/morda2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RAMIE, GFXG::GOSTEK, "gostek-gfx/ramie.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RAMIE2, GFXG::GOSTEK, "gostek-gfx/ramie2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_REKA, GFXG::GOSTEK, "gostek-gfx/reka.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_REKA2, GFXG::GOSTEK, "gostek-gfx/reka2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_DLON, GFXG::GOSTEK, "gostek-gfx/dlon.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_DLON2, GFXG::GOSTEK, "gostek-gfx/dlon2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_LANCUCH, GFXG::GOSTEK, "gostek-gfx/lancuch.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HELM, GFXG::GOSTEK, "gostek-gfx/helm.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HELM2, GFXG::GOSTEK, "gostek-gfx/helm2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_BADGE, GFXG::GOSTEK, "gostek-gfx/badge.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_BADGE2, GFXG::GOSTEK, "gostek-gfx/badge2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_CYGARO, GFXG::GOSTEK, "gostek-gfx/cygaro.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_CYGARO2, GFXG::GOSTEK, "gostek-gfx/cygaro2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_METAL, GFXG::GOSTEK, "gostek-gfx/metal.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_METAL2, GFXG::GOSTEK, "gostek-gfx/metal2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_ZLOTO, GFXG::GOSTEK, "gostek-gfx/zloto.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_ZLOTO2, GFXG::GOSTEK, "gostek-gfx/zloto2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_ZLOTYLANCUCH, GFXG::GOSTEK, "gostek-gfx/zlotylancuch.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_KAP, GFXG::GOSTEK, "gostek-gfx/kap.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_KAP2, GFXG::GOSTEK, "gostek-gfx/kap2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_DRED, GFXG::GOSTEK, "gostek-gfx/dred.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR1, GFXG::GOSTEK, "gostek-gfx/hair1.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR12, GFXG::GOSTEK, "gostek-gfx/hair12.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR2, GFXG::GOSTEK, "gostek-gfx/hair2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR22, GFXG::GOSTEK, "gostek-gfx/hair22.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR3, GFXG::GOSTEK, "gostek-gfx/hair3.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR32, GFXG::GOSTEK, "gostek-gfx/hair32.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR4, GFXG::GOSTEK, "gostek-gfx/hair4.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_HAIR42, GFXG::GOSTEK, "gostek-gfx/hair42.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_KAMIZELKA, GFXG::GOSTEK, "gostek-gfx/kamizelka.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_KAMIZELKA2, GFXG::GOSTEK, "gostek-gfx/kamizelka2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_KLATA, GFXG::GOSTEK, "gostek-gfx/ranny/klata.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_KLATA2, GFXG::GOSTEK, "gostek-gfx/ranny/klata2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_MORDA, GFXG::GOSTEK, "gostek-gfx/ranny/morda.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_MORDA2, GFXG::GOSTEK, "gostek-gfx/ranny/morda2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_NOGA, GFXG::GOSTEK, "gostek-gfx/ranny/noga.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_NOGA2, GFXG::GOSTEK, "gostek-gfx/ranny/noga2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_RAMIE, GFXG::GOSTEK, "gostek-gfx/ranny/ramie.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_RAMIE2, GFXG::GOSTEK, "gostek-gfx/ranny/ramie2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_REKA, GFXG::GOSTEK, "gostek-gfx/ranny/reka.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_REKA2, GFXG::GOSTEK, "gostek-gfx/ranny/reka2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_UDO, GFXG::GOSTEK, "gostek-gfx/ranny/udo.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_UDO2, GFXG::GOSTEK, "gostek-gfx/ranny/udo2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_BIODRO, GFXG::GOSTEK, "gostek-gfx/ranny/biodro.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_RANNY_BIODRO2, GFXG::GOSTEK, "gostek-gfx/ranny/biodro2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_LECISTOPA, GFXG::GOSTEK, "gostek-gfx/lecistopa.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_LECISTOPA2, GFXG::GOSTEK, "gostek-gfx/lecistopa2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_STOPA, GFXG::GOSTEK, "gostek-gfx/team2/stopa.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_STOPA2, GFXG::GOSTEK, "gostek-gfx/team2/stopa2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_NOGA, GFXG::GOSTEK, "gostek-gfx/team2/noga.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_NOGA2, GFXG::GOSTEK, "gostek-gfx/team2/noga2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_UDO, GFXG::GOSTEK, "gostek-gfx/team2/udo.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_UDO2, GFXG::GOSTEK, "gostek-gfx/team2/udo2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_BIODRO, GFXG::GOSTEK, "gostek-gfx/team2/biodro.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_BIODRO2, GFXG::GOSTEK, "gostek-gfx/team2/biodro2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_KLATA, GFXG::GOSTEK, "gostek-gfx/team2/klata.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_KLATA2, GFXG::GOSTEK, "gostek-gfx/team2/klata2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_MORDA, GFXG::GOSTEK, "gostek-gfx/team2/morda.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_MORDA2, GFXG::GOSTEK, "gostek-gfx/team2/morda2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RAMIE, GFXG::GOSTEK, "gostek-gfx/team2/ramie.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RAMIE2, GFXG::GOSTEK, "gostek-gfx/team2/ramie2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_REKA, GFXG::GOSTEK, "gostek-gfx/team2/reka.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_REKA2, GFXG::GOSTEK, "gostek-gfx/team2/reka2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_DLON, GFXG::GOSTEK, "gostek-gfx/team2/dlon.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_DLON2, GFXG::GOSTEK, "gostek-gfx/team2/dlon2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_LANCUCH, GFXG::GOSTEK, "gostek-gfx/team2/lancuch.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HELM, GFXG::GOSTEK, "gostek-gfx/team2/helm.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HELM2, GFXG::GOSTEK, "gostek-gfx/team2/helm2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_BADGE, GFXG::GOSTEK, "gostek-gfx/team2/badge.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_BADGE2, GFXG::GOSTEK, "gostek-gfx/team2/badge2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_CYGARO, GFXG::GOSTEK, "gostek-gfx/team2/cygaro.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_CYGARO2, GFXG::GOSTEK, "gostek-gfx/team2/cygaro2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_METAL, GFXG::GOSTEK, "gostek-gfx/team2/metal.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_METAL2, GFXG::GOSTEK, "gostek-gfx/team2/metal2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_ZLOTO, GFXG::GOSTEK, "gostek-gfx/team2/zloto.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_ZLOTO2, GFXG::GOSTEK, "gostek-gfx/team2/zloto2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_ZLOTYLANCUCH, GFXG::GOSTEK, "gostek-gfx/team2/zlotylancuch.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_KAP, GFXG::GOSTEK, "gostek-gfx/team2/kap.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_KAP2, GFXG::GOSTEK, "gostek-gfx/team2/kap2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_DRED, GFXG::GOSTEK, "gostek-gfx/team2/dred.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR1, GFXG::GOSTEK, "gostek-gfx/team2/hair1.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR12, GFXG::GOSTEK, "gostek-gfx/team2/hair12.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR2, GFXG::GOSTEK, "gostek-gfx/team2/hair2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR22, GFXG::GOSTEK, "gostek-gfx/team2/hair22.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR3, GFXG::GOSTEK, "gostek-gfx/team2/hair3.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR32, GFXG::GOSTEK, "gostek-gfx/team2/hair32.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR4, GFXG::GOSTEK, "gostek-gfx/team2/hair4.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_HAIR42, GFXG::GOSTEK, "gostek-gfx/team2/hair42.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_KAMIZELKA, GFXG::GOSTEK, "gostek-gfx/team2/kamizelka.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_KAMIZELKA2, GFXG::GOSTEK, "gostek-gfx/team2/kamizelka2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_KLATA, GFXG::GOSTEK, "gostek-gfx/team2/ranny/klata.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_KLATA2, GFXG::GOSTEK, "gostek-gfx/team2/ranny/klata2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_MORDA, GFXG::GOSTEK, "gostek-gfx/team2/ranny/morda.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_MORDA2, GFXG::GOSTEK, "gostek-gfx/team2/ranny/morda2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_NOGA, GFXG::GOSTEK, "gostek-gfx/team2/ranny/noga.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_NOGA2, GFXG::GOSTEK, "gostek-gfx/team2/ranny/noga2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_RAMIE, GFXG::GOSTEK, "gostek-gfx/team2/ranny/ramie.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_RAMIE2, GFXG::GOSTEK, "gostek-gfx/team2/ranny/ramie2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_REKA, GFXG::GOSTEK, "gostek-gfx/team2/ranny/reka.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_REKA2, GFXG::GOSTEK, "gostek-gfx/team2/ranny/reka2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_UDO, GFXG::GOSTEK, "gostek-gfx/team2/ranny/udo.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_UDO2, GFXG::GOSTEK, "gostek-gfx/team2/ranny/udo2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_BIODRO, GFXG::GOSTEK, "gostek-gfx/team2/ranny/biodro.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_RANNY_BIODRO2, GFXG::GOSTEK, "gostek-gfx/team2/ranny/biodro2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_LECISTOPA, GFXG::GOSTEK, "gostek-gfx/team2/lecistopa.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_TEAM2_LECISTOPA2, GFXG::GOSTEK, "gostek-gfx/team2/lecistopa2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_PARA_ROPE, GFXG::GOSTEK, "gostek-gfx/para-rope.bmp", 0xFF000000},
  GfxDataEntry{GFX::GOSTEK_PARA, GFXG::GOSTEK, "gostek-gfx/para.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::GOSTEK_PARA2, GFXG::GOSTEK, "gostek-gfx/para2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SHELL, GFXG::WEAPONS, "weapons-gfx/shell.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BULLET, GFXG::WEAPONS, "weapons-gfx/bullet.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SMUDGE, GFXG::WEAPONS, "weapons-gfx/smudge.bmp", 0xFF000000},
  GfxDataEntry{GFX::WEAPONS_MISSILE, GFXG::WEAPONS, "weapons-gfx/missile.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_CLUSTER, GFXG::WEAPONS, "weapons-gfx/cluster.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_CLUSTER_GRENADE, GFXG::WEAPONS, "weapons-gfx/cluster-grenade.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_FRAG_GRENADE, GFXG::WEAPONS, "weapons-gfx/frag-grenade.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_AK74, GFXG::WEAPONS, "weapons-gfx/ak74.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_AK74_2, GFXG::WEAPONS, "weapons-gfx/ak74-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_AK74_CLIP, GFXG::WEAPONS, "weapons-gfx/ak74-clip.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_AK74_CLIP2, GFXG::WEAPONS, "weapons-gfx/ak74-clip2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_AK74_SHELL, GFXG::WEAPONS, "weapons-gfx/ak74-shell.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_AK74_BULLET, GFXG::WEAPONS, "weapons-gfx/ak74-bullet.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_AK74_FIRE, GFXG::WEAPONS, "weapons-gfx/ak74-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIMI, GFXG::WEAPONS, "weapons-gfx/m249.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIMI_2, GFXG::WEAPONS, "weapons-gfx/m249-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIMI_CLIP, GFXG::WEAPONS, "weapons-gfx/m249-clip.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIMI_CLIP2, GFXG::WEAPONS, "weapons-gfx/m249-clip2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIMI_SHELL, GFXG::WEAPONS, "weapons-gfx/m249-shell.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIMI_BULLET, GFXG::WEAPONS, "weapons-gfx/m249-bullet.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIMI_FIRE, GFXG::WEAPONS, "weapons-gfx/m249-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_RUGER, GFXG::WEAPONS, "weapons-gfx/ruger77.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_RUGER_2, GFXG::WEAPONS, "weapons-gfx/ruger77-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_RUGER_SHELL, GFXG::WEAPONS, "weapons-gfx/ruger77-shell.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_RUGER_BULLET, GFXG::WEAPONS, "weapons-gfx/ruger77-bullet.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_RUGER_FIRE, GFXG::WEAPONS, "weapons-gfx/ruger77-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MP5, GFXG::WEAPONS, "weapons-gfx/mp5.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MP5_2, GFXG::WEAPONS, "weapons-gfx/mp5-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MP5_CLIP, GFXG::WEAPONS, "weapons-gfx/mp5-clip.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MP5_CLIP2, GFXG::WEAPONS, "weapons-gfx/mp5-clip2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MP5_SHELL, GFXG::WEAPONS, "weapons-gfx/mp5-shell.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MP5_BULLET, GFXG::WEAPONS, "weapons-gfx/mp5-bullet.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MP5_FIRE, GFXG::WEAPONS, "weapons-gfx/mp5-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SPAS, GFXG::WEAPONS, "weapons-gfx/spas12.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SPAS_2, GFXG::WEAPONS, "weapons-gfx/spas12-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SPAS_SHELL, GFXG::WEAPONS, "weapons-gfx/spas12-shell.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SPAS_BULLET, GFXG::WEAPONS, "weapons-gfx/spas12-bullet.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SPAS_FIRE, GFXG::WEAPONS, "weapons-gfx/spas12-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M79, GFXG::WEAPONS, "weapons-gfx/m79.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M79_2, GFXG::WEAPONS, "weapons-gfx/m79-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M79_CLIP, GFXG::WEAPONS, "weapons-gfx/m79-clip.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M79_CLIP2, GFXG::WEAPONS, "weapons-gfx/m79-clip2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M79_SHELL, GFXG::WEAPONS, "weapons-gfx/m79-shell.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M79_BULLET, GFXG::WEAPONS, "weapons-gfx/m79-bullet.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M79_FIRE, GFXG::WEAPONS, "weapons-gfx/m79-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_DEAGLES, GFXG::WEAPONS, "weapons-gfx/deserteagle.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_DEAGLES_2, GFXG::WEAPONS, "weapons-gfx/deserteagle-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_N_DEAGLES, GFXG::WEAPONS, "weapons-gfx/n-deserteagle.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_N_DEAGLES_2, GFXG::WEAPONS, "weapons-gfx/n-deserteagle-2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_DEAGLES_CLIP, GFXG::WEAPONS, "weapons-gfx/deserteagle-clip.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_DEAGLES_CLIP2, GFXG::WEAPONS, "weapons-gfx/deserteagle-clip2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_DEAGLES_SHELL, GFXG::WEAPONS, "weapons-gfx/eagles-shell.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_DEAGLES_BULLET, GFXG::WEAPONS, "weapons-gfx/eagles-bullet.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_DEAGLES_FIRE, GFXG::WEAPONS, "weapons-gfx/eagles-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_STEYR, GFXG::WEAPONS, "weapons-gfx/steyraug.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_STEYR_2, GFXG::WEAPONS, "weapons-gfx/steyraug-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_STEYR_CLIP, GFXG::WEAPONS, "weapons-gfx/steyraug-clip.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_STEYR_CLIP2, GFXG::WEAPONS, "weapons-gfx/steyraug-clip2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_STEYR_SHELL, GFXG::WEAPONS, "weapons-gfx/steyraug-shell.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_STEYR_BULLET, GFXG::WEAPONS, "weapons-gfx/steyraug-bullet.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_STEYR_FIRE, GFXG::WEAPONS, "weapons-gfx/steyraug-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BARRETT, GFXG::WEAPONS, "weapons-gfx/barretm82.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BARRETT_2, GFXG::WEAPONS, "weapons-gfx/barretm82-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BARRETT_CLIP, GFXG::WEAPONS, "weapons-gfx/barretm82-clip.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BARRETT_CLIP2, GFXG::WEAPONS, "weapons-gfx/barretm82-clip2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BARRETT_SHELL, GFXG::WEAPONS, "weapons-gfx/barretm82-shell.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BARRETT_BULLET, GFXG::WEAPONS, "weapons-gfx/barretm82-bullet.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BARRETT_FIRE, GFXG::WEAPONS, "weapons-gfx/barret-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIGUN, GFXG::WEAPONS, "weapons-gfx/minigun.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIGUN_2, GFXG::WEAPONS, "weapons-gfx/minigun-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIGUN_CLIP, GFXG::WEAPONS, "weapons-gfx/minigun-clip.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIGUN_SHELL, GFXG::WEAPONS, "weapons-gfx/minigun-shell.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIGUN_BULLET, GFXG::WEAPONS, "weapons-gfx/minigun-bullet.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_MINIGUN_FIRE, GFXG::WEAPONS, "weapons-gfx/minigun-fire.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SOCOM, GFXG::WEAPONS, "weapons-gfx/colt1911.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SOCOM_2, GFXG::WEAPONS, "weapons-gfx/colt1911-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_N_SOCOM, GFXG::WEAPONS, "weapons-gfx/n-colt1911.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_N_SOCOM_2, GFXG::WEAPONS, "weapons-gfx/n-colt1911-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SOCOM_CLIP, GFXG::WEAPONS, "weapons-gfx/colt1911-clip.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SOCOM_CLIP2, GFXG::WEAPONS, "weapons-gfx/colt1911-clip2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_COLT_SHELL, GFXG::WEAPONS, "weapons-gfx/colt-shell.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_COLT_BULLET, GFXG::WEAPONS, "weapons-gfx/colt-bullet.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_SOCOM_FIRE, GFXG::WEAPONS, "weapons-gfx/colt1911-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BOW, GFXG::WEAPONS, "weapons-gfx/bow.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BOW_2, GFXG::WEAPONS, "weapons-gfx/bow-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BOW_S, GFXG::WEAPONS, "weapons-gfx/bow-s.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BOW_A, GFXG::WEAPONS, "weapons-gfx/bow-a.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_N_BOW, GFXG::WEAPONS, "weapons-gfx/n-bow.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_N_BOW_2, GFXG::WEAPONS, "weapons-gfx/n-bow-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_ARROW, GFXG::WEAPONS, "weapons-gfx/arrow.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_BOW_FIRE, GFXG::WEAPONS, "weapons-gfx/bow-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_FLAMER, GFXG::WEAPONS, "weapons-gfx/flamer.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_FLAMER_2, GFXG::WEAPONS, "weapons-gfx/flamer-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_FLAMER_FIRE, GFXG::WEAPONS, "weapons-gfx/flamer-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_KNIFE, GFXG::WEAPONS, "weapons-gfx/knife.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_KNIFE2, GFXG::WEAPONS, "weapons-gfx/knife2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_CHAINSAW, GFXG::WEAPONS, "weapons-gfx/chainsaw.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_CHAINSAW2, GFXG::WEAPONS, "weapons-gfx/chainsaw2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_CHAINSAW_FIRE, GFXG::WEAPONS, "weapons-gfx/chainsaw-fire.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_LAW, GFXG::WEAPONS, "weapons-gfx/law.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_LAW_2, GFXG::WEAPONS, "weapons-gfx/law-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_LAW_FIRE, GFXG::WEAPONS, "weapons-gfx/law-fire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M2, GFXG::WEAPONS, "weapons-gfx/m2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M2_2, GFXG::WEAPONS, "weapons-gfx/m2-2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::WEAPONS_M2_STAT, GFXG::WEAPONS, "weapons-gfx/m2-stat.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_SMOKE, GFXG::SPARKS, "sparks-gfx/smoke.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_LILFIRE, GFXG::SPARKS, "sparks-gfx/lilfire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_ODPRYSK, GFXG::SPARKS, "sparks-gfx/odprysk.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_BLOOD, GFXG::SPARKS, "sparks-gfx/blood.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE1, GFXG::SPARKS, "sparks-gfx/explosion/explode1.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE2, GFXG::SPARKS, "sparks-gfx/explosion/explode2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE3, GFXG::SPARKS, "sparks-gfx/explosion/explode3.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE4, GFXG::SPARKS, "sparks-gfx/explosion/explode4.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE5, GFXG::SPARKS, "sparks-gfx/explosion/explode5.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE6, GFXG::SPARKS, "sparks-gfx/explosion/explode6.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE7, GFXG::SPARKS, "sparks-gfx/explosion/explode7.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE8, GFXG::SPARKS, "sparks-gfx/explosion/explode8.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE9, GFXG::SPARKS, "sparks-gfx/explosion/explode9.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE10, GFXG::SPARKS, "sparks-gfx/explosion/explode10.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE11, GFXG::SPARKS, "sparks-gfx/explosion/explode11.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE12, GFXG::SPARKS, "sparks-gfx/explosion/explode12.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE13, GFXG::SPARKS, "sparks-gfx/explosion/explode13.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE14, GFXG::SPARKS, "sparks-gfx/explosion/explode14.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE15, GFXG::SPARKS, "sparks-gfx/explosion/explode15.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_EXPLODE16, GFXG::SPARKS, "sparks-gfx/explosion/explode16.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_BIGSMOKE, GFXG::SPARKS, "sparks-gfx/bigsmoke.bmp", 0xFF000000},
  GfxDataEntry{GFX::SPARKS_SPAWNSPARK, GFXG::SPARKS, "sparks-gfx/spawnspark.bmp", 0xFF000000},
  GfxDataEntry{GFX::SPARKS_PIN, GFXG::SPARKS, "sparks-gfx/pin.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_LILSMOKE, GFXG::SPARKS, "sparks-gfx/lilsmoke.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_STUFF, GFXG::SPARKS, "sparks-gfx/stuff.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_CYGARO, GFXG::SPARKS, "sparks-gfx/cygaro.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_PLOMYK, GFXG::SPARKS, "sparks-gfx/plomyk.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_BLACKSMOKE, GFXG::SPARKS, "sparks-gfx/blacksmoke.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_RAIN, GFXG::SPARKS, "sparks-gfx/rain.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_SAND, GFXG::SPARKS, "sparks-gfx/sand.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_ODLAMEK1, GFXG::SPARKS, "sparks-gfx/odlamek1.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_ODLAMEK2, GFXG::SPARKS, "sparks-gfx/odlamek2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_ODLAMEK3, GFXG::SPARKS, "sparks-gfx/odlamek3.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_ODLAMEK4, GFXG::SPARKS, "sparks-gfx/odlamek4.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_SKRAWEK, GFXG::SPARKS, "sparks-gfx/skrawek.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_PUFF, GFXG::SPARKS, "sparks-gfx/puff.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_SNOW, GFXG::SPARKS, "sparks-gfx/snow.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE1, GFXG::SPARKS, "sparks-gfx/explosion/smoke1.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE2, GFXG::SPARKS, "sparks-gfx/explosion/smoke2.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE3, GFXG::SPARKS, "sparks-gfx/explosion/smoke3.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE4, GFXG::SPARKS, "sparks-gfx/explosion/smoke4.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE5, GFXG::SPARKS, "sparks-gfx/explosion/smoke5.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE6, GFXG::SPARKS, "sparks-gfx/explosion/smoke6.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE7, GFXG::SPARKS, "sparks-gfx/explosion/smoke7.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE8, GFXG::SPARKS, "sparks-gfx/explosion/smoke8.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_EXPLOSION_SMOKE9, GFXG::SPARKS, "sparks-gfx/explosion/smoke9.bmp",
               0xFF000000},
  GfxDataEntry{GFX::SPARKS_SPLAT, GFXG::SPARKS, "sparks-gfx/splat.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_MINISMOKE, GFXG::SPARKS, "sparks-gfx/minismoke.bmp", 0xFF000000},
  GfxDataEntry{GFX::SPARKS_BIGSMOKE2, GFXG::SPARKS, "sparks-gfx/bigsmoke2.bmp", 0xFF000000},
  GfxDataEntry{GFX::SPARKS_JETFIRE, GFXG::SPARKS, "sparks-gfx/jetfire.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_LILBLOOD, GFXG::SPARKS, "sparks-gfx/lilblood.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE1, GFXG::SPARKS, "sparks-gfx/flames/explode1.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE2, GFXG::SPARKS, "sparks-gfx/flames/explode2.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE3, GFXG::SPARKS, "sparks-gfx/flames/explode3.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE4, GFXG::SPARKS, "sparks-gfx/flames/explode4.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE5, GFXG::SPARKS, "sparks-gfx/flames/explode5.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE6, GFXG::SPARKS, "sparks-gfx/flames/explode6.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE7, GFXG::SPARKS, "sparks-gfx/flames/explode7.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE8, GFXG::SPARKS, "sparks-gfx/flames/explode8.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE9, GFXG::SPARKS, "sparks-gfx/flames/explode9.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE10, GFXG::SPARKS, "sparks-gfx/flames/explode10.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE11, GFXG::SPARKS, "sparks-gfx/flames/explode11.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE12, GFXG::SPARKS, "sparks-gfx/flames/explode12.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE13, GFXG::SPARKS, "sparks-gfx/flames/explode13.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE14, GFXG::SPARKS, "sparks-gfx/flames/explode14.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE15, GFXG::SPARKS, "sparks-gfx/flames/explode15.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::SPARKS_FLAMES_EXPLODE16, GFXG::SPARKS, "sparks-gfx/flames/explode16.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_SIGHT, GFXG::INTERFACE, "interface-gfx/sight.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_DEAGLES, GFXG::INTERFACE, "interface-gfx/guns/1.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_MP5, GFXG::INTERFACE, "interface-gfx/guns/2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_AK74, GFXG::INTERFACE, "interface-gfx/guns/3.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_STEYR, GFXG::INTERFACE, "interface-gfx/guns/4.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_SPAS, GFXG::INTERFACE, "interface-gfx/guns/5.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_RUGER, GFXG::INTERFACE, "interface-gfx/guns/6.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_M79, GFXG::INTERFACE, "interface-gfx/guns/7.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_BARRETT, GFXG::INTERFACE, "interface-gfx/guns/8.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_MINIMI, GFXG::INTERFACE, "interface-gfx/guns/9.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_MINIGUN, GFXG::INTERFACE, "interface-gfx/guns/0.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_SOCOM, GFXG::INTERFACE, "interface-gfx/guns/10.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_KNIFE, GFXG::INTERFACE, "interface-gfx/guns/knife.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_CHAINSAW, GFXG::INTERFACE, "interface-gfx/guns/chainsaw.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_LAW, GFXG::INTERFACE, "interface-gfx/guns/law.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_FLAMER, GFXG::INTERFACE, "interface-gfx/guns/flamer.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_BOW, GFXG::INTERFACE, "interface-gfx/guns/bow.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_FIST, GFXG::INTERFACE, "interface-gfx/guns/fist.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_GUNS_M2, GFXG::INTERFACE, "interface-gfx/guns/m2.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_STAR, GFXG::INTERFACE, "interface-gfx/star.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_FRIEND, GFXG::INTERFACE, "interface-gfx/friend.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_MIC, GFXG::INTERFACE, "interface-gfx/mic.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_CONNECTION, GFXG::INTERFACE, "interface-gfx/connection.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_SMALLDOT, GFXG::INTERFACE, "interface-gfx/smalldot.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_DEADDOT, GFXG::INTERFACE, "interface-gfx/deaddot.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_MUTE, GFXG::INTERFACE, "interface-gfx/mute.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_PROT, GFXG::INTERFACE, "interface-gfx/prot.png", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_SCROLL, GFXG::INTERFACE, "interface-gfx/scroll.png", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_BOT, GFXG::INTERFACE, "interface-gfx/bot.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_CURSOR, GFXG::INTERFACE, "interface-gfx/cursor.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_HEALTH, GFXG::INTERFACE, "interface-gfx/health.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_AMMO, GFXG::INTERFACE, "interface-gfx/ammo.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_JET, GFXG::INTERFACE, "interface-gfx/jet.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_HEALTH_BAR, GFXG::INTERFACE, "interface-gfx/health-bar.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_JET_BAR, GFXG::INTERFACE, "interface-gfx/jet-bar.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_RELOAD_BAR, GFXG::INTERFACE, "interface-gfx/reload-bar.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_BACK, GFXG::INTERFACE, "interface-gfx/back.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_OVERLAY, GFXG::INTERFACE, "interface-gfx/overlay.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_NADE, GFXG::INTERFACE, "interface-gfx/nade.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_NOFLAG, GFXG::INTERFACE, "interface-gfx/noflag.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_FLAG, GFXG::INTERFACE, "interface-gfx/flag.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_CLUSTER_NADE, GFXG::INTERFACE, "interface-gfx/cluster-nade.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_DOT, GFXG::INTERFACE, "interface-gfx/dot.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_FIRE_BAR, GFXG::INTERFACE, "interface-gfx/fire-bar.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_FIRE_BAR_R, GFXG::INTERFACE, "interface-gfx/fire-bar-r.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_VEST_BAR, GFXG::INTERFACE, "interface-gfx/vest-bar.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_MENUCURSOR, GFXG::INTERFACE, "interface-gfx/menucursor.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_ARROW, GFXG::INTERFACE, "interface-gfx/arrow.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_TITLE_L, GFXG::INTERFACE, "interface-gfx/title-l.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::INTERFACE_TITLE_R, GFXG::INTERFACE, "interface-gfx/title-r.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_FLAG, GFXG::OBJECTS, "textures/objects/flag.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_INFFLAG, GFXG::OBJECTS, "textures/objects/infflag.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_MEDIKIT, GFXG::OBJECTS, "textures/objects/medikit.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_GRENADEKIT, GFXG::OBJECTS, "textures/objects/grenadekit.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_FLAMERKIT, GFXG::OBJECTS, "textures/objects/flamerkit.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_PREDATORKIT, GFXG::OBJECTS, "textures/objects/predatorkit.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_VESTKIT, GFXG::OBJECTS, "textures/objects/vestkit.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_BERSERKERKIT, GFXG::OBJECTS, "textures/objects/berserkerkit.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_CLUSTERKIT, GFXG::OBJECTS, "textures/objects/clusterkit.bmp",
               0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_ILUM, GFXG::OBJECTS, "objects-gfx/ilum.bmp", 0xFF00FF00},
  GfxDataEntry{GFX::OBJECTS_FLAG_HANDLE, GFXG::OBJECTS, "objects-gfx/flag.bmp", 0xFF00FF00}};
